2023-01-10 09:44:31,320 frame11 INFO     opening browser
2023-01-10 09:45:01,857 frame11 INFO     getting element for login button
2023-01-10 09:45:03,869 frame11 ERROR    Unable to locate element login button
Traceback (most recent call last):
  File "e:\PYTHON\irctc_v3\frame1.py", line 77, in start1
    wait.until(EC.element_to_be_clickable((By.XPATH, '/html/body/app-root/app-home/div[1]/app-header/div[1]/div[3]/div/a[2]'))).click()
  File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 297, in __call__
    element = visibility_of_element_located(self.locator)(driver)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 128, in __call__
    return _element_if_visible(_find_element(driver, self.locator))
  File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 415, in _find_element
    raise e
  File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=108.0.5359.128)

2023-01-10 09:45:05,897 frame11 INFO     username click
2023-01-10 09:45:05,897 frame11 ERROR    error in username enter
Traceback (most recent call last):
  File "e:\PYTHON\irctc_v3\frame1.py", line 96, in start1
    element3=wait.until(EC.presence_of_element_located((By.XPATH, '/html/body/app-root/app-home/div[3]/app-login/p-dialog[1]/div/div/div[2]/div[2]/div/div[2]/div[2]/div[2]/form/div[1]/input')))
  File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 64, in __call__
    return _find_element(driver, self.locator)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 415, in _find_element
    raise e
  File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=108.0.5359.128)

2023-01-10 09:45:05,897 frame11 INFO     password element find
2023-01-10 09:45:05,897 frame11 ERROR    error in password enter
Traceback (most recent call last):
  File "e:\PYTHON\irctc_v3\frame1.py", line 114, in start1
    element4=wait.until(EC.presence_of_element_located((By.XPATH, '/html/body/app-root/app-home/div[3]/app-login/p-dialog[1]/div/div/div[2]/div[2]/div/div[2]/div[2]/div[2]/form/div[2]/input')))
  File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\support\wait.py", line 71, in until
    value = method(self._driver)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 64, in __call__
    return _find_element(driver, self.locator)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 415, in _find_element
    raise e
  File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\support\expected_conditions.py", line 411, in _find_element
    return driver.find_element(*by)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 976, in find_element
    return self.execute(Command.FIND_ELEMENT, {
  File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\dell\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=108.0.5359.128)

2023-01-10 09:45:05,897 frame11 INFO     getting login captcha
2023-01-10 09:59:56,733 frame11 INFO     opening browser
2023-01-10 10:00:15,986 frame11 INFO     getting element for login button
2023-01-10 10:00:21,393 frame11 INFO     username click
2023-01-10 10:00:23,909 frame11 INFO     username entered
2023-01-10 10:00:23,909 frame11 INFO     password element find
2023-01-10 10:00:24,525 frame11 INFO     password entered
2023-01-10 10:00:24,525 frame11 INFO     getting login captcha
2023-01-10 10:00:34,713 frame11 INFO     captcha entered
2023-01-10 10:00:41,966 frame11 INFO     login done
2023-01-10 10:00:41,966 frame11 INFO     getting FROM route element
2023-01-10 10:00:44,046 frame11 INFO     getting TO route element
2023-01-10 10:00:47,471 frame11 INFO     getting date element
2023-01-10 10:00:48,769 frame11 INFO     tatkal click
2023-01-10 10:00:49,321 frame11 INFO     train search start
2023-01-10 10:00:49,662 frame11 INFO     train select page
2023-01-10 10:00:49,662 frame11 INFO     refresh train button
2023-01-10 10:00:55,287 frame11 INFO     choose train button
2023-01-10 10:00:55,527 frame11 INFO     book button click
2023-01-10 10:00:59,500 frame11 INFO     -------passanger detail filling page-------- 
2023-01-10 10:00:59,500 frame11 INFO     passanger 1 detail filling
2023-01-10 10:01:00,260 frame11 INFO     name enter
2023-01-10 10:01:02,867 frame11 INFO     age enter
2023-01-10 10:01:03,459 frame11 INFO     gender select
2023-01-10 10:01:04,083 frame11 INFO     food choose
2023-01-10 10:01:04,083 frame11 INFO     upi payment start
2023-01-10 10:01:18,840 frame11 INFO     upi payment captcha page
2023-01-10 10:01:28,915 frame11 INFO     upi payment captcha enter
2023-01-10 10:01:29,097 frame11 INFO     upi continue_button
2023-01-10 10:01:32,107 frame11 ERROR    error in payment captcha page
Traceback (most recent call last):
  File "e:\PYTHON\irctc_v3\frame1.py", line 793, in upi_function
    paycaptcha2()
  File "e:\PYTHON\irctc_v3\frame1.py", line 788, in paycaptcha2
    error_check()
NameError: free variable 'error_check' referenced before assignment in enclosing scope
2023-01-10 10:01:34,158 frame11 INFO     Multiple Payment Service
2023-01-10 10:01:34,638 frame11 INFO     roserpay method
2023-01-10 10:01:34,814 frame11 INFO     getting pay & book button
2023-01-10 10:01:41,985 frame11 INFO     getting payment page
2023-01-10 10:01:46,090 frame11 INFO     click upi or QR
2023-01-10 10:01:46,378 frame11 INFO     click upi add button
2023-01-10 10:01:47,162 frame11 INFO     upi added 
2023-01-10 10:02:02,772 frame11 INFO     pay button click
2023-01-10 10:02:05,043 frame11 INFO     mobile link sending
2023-01-10 10:02:05,051 frame11 INFO     0:02:07
